[build]
  publish = "."
  # root website directory
  command = "echo 'I be building'"
  # the build command

[[redirects]]
  from = "/api/places/*"
  to = "https://maps.googleapis.com/maps/api/place/findplacefromtext/:splat"
  status = 200